(()=>{
  const CORE='https://raw.githubusercontent.com/slowpoison05/Dattacity.in/d2259a62c81e7fa9da3052e4007aeaa460210e37/app-modern.js';
  const V='9.23.0';
  const SDK=[`https://www.gstatic.com/firebasejs/${V}/firebase-app-compat.js`,`https://www.gstatic.com/firebasejs/${V}/firebase-auth-compat.js`,`https://www.gstatic.com/firebasejs/${V}/firebase-database-compat.js`,`https://www.gstatic.com/firebasejs/${V}/firebase-storage-compat.js`];
  const CFG={apiKey:'AIzaSyCvaXtUjp8xY5nRFXroL-H1ospFSgM7qQ0',authDomain:'superkisan-33b7e.firebaseapp.com',databaseURL:'https://superkisan-33b7e-default-rtdb.firebaseio.com',projectId:'superkisan-33b7e',storageBucket:'superkisan-33b7e.firebasestorage.app',messagingSenderId:'744234922644',appId:'1:744234922644:web:20b4c062d50d6265fdba81'};
  const esc=v=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
  const first=(v,...ks)=>ks.map(k=>v?.[k]).find(x=>x!=null&&String(x).trim()!=='');
  const photos=v=>Array.isArray(v?.photos)?v.photos.filter(Boolean):(v?.photoURL||v?.image||v?.imageUrl||v?.photo||v?.profilePhoto?[v.photoURL||v.image||v.imageUrl||v.photo||v.profilePhoto]:[]);
  function status(t){const e=document.getElementById('dbStatus');if(e)e.textContent=t}
  function load(src){return new Promise((ok,bad)=>{const s=document.createElement('script');s.src=src;s.onload=ok;s.onerror=()=>bad(Error('Firebase SDK failed: '+src));document.head.appendChild(s)})}
  async function firebaseReady(){if(!window.firebase?.initializeApp)for(const s of SDK)await load(s);if(!window.firebase)throw Error('Firebase SDK unavailable');if(!firebase.apps.length)firebase.initializeApp(CFG);return firebase}
  function inject(){if(document.getElementById('dattacity-existing-services'))return;const home=document.getElementById('home');if(!home)return;const sec=document.createElement('section');sec.id='dattacity-existing-services';sec.className='section';sec.innerHTML='<div class="sectionHead"><div><div class="kicker">EXISTING DATTACITY SERVICES</div><h2>Local services, kept intact.</h2><p class="sectionLead">Connected to the existing Firebase database.</p></div></div><div id="dcServicesList" class="cards"></div>';home.appendChild(sec);const kh=document.createElement('section');kh.className='section';kh.innerHTML='<div class="cta" style="margin-top:0"><div><div class="kicker" style="color:#ead6a5">FARMER SUPPORT</div><h2>Kheti Health Centre</h2><p>Open the existing farmer-focused health centre.</p></div><button type="button" id="khetiHealthBtn">Open Kheti Health Centre ↗</button></div>';home.appendChild(kh);document.getElementById('khetiHealthBtn').onclick=()=>location.href='https://kheti.dattacity.in'}
  function render(rows){const list=document.getElementById('servicesList')||document.getElementById('dcServicesList');if(!list)return;if(!rows.length){list.innerHTML='<div class="notice">No services found.</div>';return}list.innerHTML=rows.map(x=>{const n=first(x,'name','title','serviceName')||'Local service',c=first(x,'category','type','serviceType')||'Service',d=first(x,'details','description','about')||'',p=first(x,'phone','mobile','contact','phoneNumber'),im=photos(x)[0];return `<article class="card"><div class="row">${im?`<img class="thumb" src="${esc(im)}" alt="">`:'<div class="thumb">◉</div>'}<div class="info"><h3>${esc(n)}</h3><div class="muted">${esc(d)}</div><span class="tag">${esc(c)}</span>${p?`<div class="actions"><a class="call" href="tel:${esc(p)}">Call</a></div>`:''}</div></div></article>`}).join('')}
  async function start(){status('Connecting…');try{const f=await firebaseReady();const db=f.database();inject();db.ref('services').on('value',s=>{const rows=[];s.forEach(c=>{const v=c.val();if(v&&typeof v==='object')rows.push(v)});render(rows);const count=document.getElementById('serviceCount');if(count)count.textContent=rows.length;status('Connected')},e=>{console.error(e);status('Firebase error')});let code=await fetch(CORE,{cache:'no-store'}).then(r=>{if(!r.ok)throw Error('Core load failed');return r.text()});code=code.replace('storage=firebase.storage();','storage=(()=>{try{return firebase.storage()}catch(e){console.warn(e);return null}})();');(0,eval)(code);if(document.readyState!=='loading')document.dispatchEvent(new Event('DOMContentLoaded'));}catch(e){console.error(e);status('Firebase error')}}
  start();
})();